import './globals.scss';

import { lato, leagueSpartan } from '@utils/fonts';

export const metadata = {
	title: 'Diamond Printers',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${lato.variable} ${leagueSpartan.variable}`}>
				{children}
			</body>
		</html>
	);
}
